# -*- coding: utf-8 -*-
"""C134 home.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9xQrc_K9sg4NGRnx3uKV5z6UT9e1c0S
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("star_with_gravity.csv")

df.head()

#filtering the stars based on distance
bools =[]
for d in df.Distance:
    if d<=100:
        bools.append(True)
    else:
        bools.append(False)

is_dist = pd.Series(bools)

is_dist.head()

star_dist=df[is_dist]

star_dist.reset_index(inplace=True,drop=True)
star_dist.head()

star_dist.shape

#keep the stars having gravity similar to sun
gravity_bool = []
for g in star_dist.Gravity:
    if g<=350 and g>=150:
        gravity_bool.append(True)
    else :
        gravity_bool.append(False)

is_gravity = pd.Series(gravity_bool)

final_stars = star_dist[is_gravity]
final_stars.head()

final_stars.shape

final_stars.reset_index(inplace=True,drop=True)

final_stars.head()

final_stars.to_csv("filtered_stars.csv")

